version: '3.8'

services:
  database:
    image: postgres:15-alpine
    container_name: qr_database
    restart: always
    environment:
      POSTGRES_USER: usuario_qr
      POSTGRES_PASSWORD: algo_bien_seguro
      POSTGRES_DB: validacion_db
    ports:
      - "5433:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: